package store

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Document statuses. See docs/plans/00-overview.md for the state machine.
const (
	StatusUploaded   = "uploaded"
	StatusProcessing = "processing"
	StatusOCRDone    = "ocr_done"
	StatusExtracting = "extracting"
	StatusExtracted  = "extracted"
	StatusFailed     = "failed"
)

// ErrNotFound is returned when a row does not exist.
var ErrNotFound = errors.New("not found")

// Document is a row of the documents table.
type Document struct {
	ID                 string
	Filename           string
	Status             string
	FailedStage        *string
	ErrorMessage       *string
	PageCount          *int
	GCSBucket          string
	GCSPDFObject       string
	OCRDispatchedAt    *time.Time
	ExtractionAttempts int
	NextExtractionAt   *time.Time
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

// Page is a row of the pages table.
type Page struct {
	ID         string
	DocumentID string
	PageNumber int
	GCSObject  string
}

// Documents provides persistence for documents and their pages.
type Documents struct {
	pool *pgxpool.Pool
}

func NewDocuments(pool *pgxpool.Pool) *Documents {
	return &Documents{pool: pool}
}

const documentColumns = `id::text, filename, status, failed_stage, error_message, page_count,
	gcs_bucket, gcs_pdf_object, ocr_dispatched_at, extraction_attempts, next_extraction_at, created_at, updated_at`

func scanDocument(row pgx.Row) (Document, error) {
	var d Document
	err := row.Scan(&d.ID, &d.Filename, &d.Status, &d.FailedStage, &d.ErrorMessage, &d.PageCount,
		&d.GCSBucket, &d.GCSPDFObject, &d.OCRDispatchedAt, &d.ExtractionAttempts, &d.NextExtractionAt, &d.CreatedAt, &d.UpdatedAt)
	if errors.Is(err, pgx.ErrNoRows) {
		return Document{}, ErrNotFound
	}
	return d, err
}

// Create inserts a new document in status "uploaded" and returns it. The ID is
// generated by the caller so GCS object names can embed it before the insert.
func (s *Documents) Create(ctx context.Context, id, filename, gcsBucket, gcsPDFObject string) (Document, error) {
	row := s.pool.QueryRow(ctx, `
		INSERT INTO documents (id, filename, gcs_bucket, gcs_pdf_object)
		VALUES ($1::uuid, $2, $3, $4)
		RETURNING `+documentColumns,
		id, filename, gcsBucket, gcsPDFObject)
	return scanDocument(row)
}

// GetByID fetches one document, returning ErrNotFound if absent.
func (s *Documents) GetByID(ctx context.Context, id string) (Document, error) {
	row := s.pool.QueryRow(ctx, `SELECT `+documentColumns+` FROM documents WHERE id = $1::uuid`, id)
	return scanDocument(row)
}

// UpdateStatus transitions a document from one status to another. It returns
// false when the document was not in the expected "from" status, which callers
// use to detect concurrent workers or stale state.
func (s *Documents) UpdateStatus(ctx context.Context, id, from, to string) (bool, error) {
	tag, err := s.pool.Exec(ctx, `
		UPDATE documents SET status = $3, updated_at = now()
		WHERE id = $1::uuid AND status = $2`,
		id, from, to)
	if err != nil {
		return false, fmt.Errorf("update status %s->%s: %w", from, to, err)
	}
	return tag.RowsAffected() == 1, nil
}

// MarkFailed transitions a document from the expected status to failed,
// recording which stage broke and why.
func (s *Documents) MarkFailed(ctx context.Context, id, from, stage, message string) (bool, error) {
	tag, err := s.pool.Exec(ctx, `
		UPDATE documents SET status = $3, failed_stage = $4, error_message = $5, updated_at = now()
		WHERE id = $1::uuid AND status = $2`,
		id, from, StatusFailed, stage, message)
	if err != nil {
		return false, fmt.Errorf("mark failed: %w", err)
	}
	return tag.RowsAffected() == 1, nil
}

// AddPages records the GCS objects of converted pages. Inserts are idempotent
// (ON CONFLICT DO NOTHING) so the janitor can safely re-run ingestion.
func (s *Documents) AddPages(ctx context.Context, documentID string, objects []string) error {
	batch := &pgx.Batch{}
	for i, obj := range objects {
		batch.Queue(`
			INSERT INTO pages (document_id, page_number, gcs_object)
			VALUES ($1::uuid, $2, $3)
			ON CONFLICT (document_id, page_number) DO NOTHING`,
			documentID, i+1, obj)
	}
	return s.pool.SendBatch(ctx, batch).Close()
}

// SetPageCount records how many pages the PDF produced.
func (s *Documents) SetPageCount(ctx context.Context, id string, n int) error {
	_, err := s.pool.Exec(ctx,
		`UPDATE documents SET page_count = $2, updated_at = now() WHERE id = $1::uuid`, id, n)
	return err
}

// PagesByDocument returns a document's pages ordered by page number.
func (s *Documents) PagesByDocument(ctx context.Context, documentID string) ([]Page, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT id::text, document_id::text, page_number, gcs_object
		FROM pages WHERE document_id = $1::uuid ORDER BY page_number`,
		documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var pages []Page
	for rows.Next() {
		var p Page
		if err := rows.Scan(&p.ID, &p.DocumentID, &p.PageNumber, &p.GCSObject); err != nil {
			return nil, err
		}
		pages = append(pages, p)
	}
	return pages, rows.Err()
}

// SetOCRDispatched stamps the moment the OCR job was handed to the OCR service.
func (s *Documents) SetOCRDispatched(ctx context.Context, id string) error {
	_, err := s.pool.Exec(ctx,
		`UPDATE documents SET ocr_dispatched_at = now(), updated_at = now() WHERE id = $1::uuid`, id)
	return err
}

// ClaimForExtraction atomically claims one document ready for LLM extraction,
// moving it to "extracting" and counting the attempt. SKIP LOCKED makes this
// safe across replicas. Returns ok=false when nothing is eligible.
func (s *Documents) ClaimForExtraction(ctx context.Context, maxAttempts int) (Document, bool, error) {
	row := s.pool.QueryRow(ctx, `
		UPDATE documents
		SET status = $2, extraction_attempts = extraction_attempts + 1, updated_at = now()
		WHERE id = (
			SELECT id FROM documents
			WHERE status = $1
			  AND (next_extraction_at IS NULL OR next_extraction_at <= now())
			  AND extraction_attempts < $3
			ORDER BY updated_at
			FOR UPDATE SKIP LOCKED
			LIMIT 1
		)
		RETURNING `+documentColumns,
		StatusOCRDone, StatusExtracting, maxAttempts)
	doc, err := scanDocument(row)
	if errors.Is(err, ErrNotFound) {
		return Document{}, false, nil
	}
	if err != nil {
		return Document{}, false, err
	}
	return doc, true, nil
}

// ReturnForRetry sends a document that failed extraction transiently back to
// the queue, eligible again after the backoff.
func (s *Documents) ReturnForRetry(ctx context.Context, id string, backoff time.Duration) error {
	_, err := s.pool.Exec(ctx, `
		UPDATE documents
		SET status = $2, next_extraction_at = now() + $3, updated_at = now()
		WHERE id = $1::uuid AND status = $4`,
		id, StatusOCRDone, backoff, StatusExtracting)
	return err
}

// FailExhausted marks documents that ran out of extraction attempts.
func (s *Documents) FailExhausted(ctx context.Context, maxAttempts int) (int64, error) {
	tag, err := s.pool.Exec(ctx, `
		UPDATE documents
		SET status = $1, failed_stage = 'extraction',
		    error_message = 'extraction attempts exhausted', updated_at = now()
		WHERE status = $2 AND extraction_attempts >= $3`,
		StatusFailed, StatusOCRDone, maxAttempts)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// StuckDocuments lists non-terminal documents that stopped making progress —
// the input of the janitor.
func (s *Documents) StuckDocuments(ctx context.Context, olderThan time.Duration) ([]Document, error) {
	rows, err := s.pool.Query(ctx, `
		SELECT `+documentColumns+` FROM documents
		WHERE status IN ($1, $2) AND updated_at < $3
		ORDER BY updated_at`,
		StatusProcessing, StatusExtracting, time.Now().Add(-olderThan))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var docs []Document
	for rows.Next() {
		d, err := scanDocument(rows)
		if err != nil {
			return nil, err
		}
		docs = append(docs, d)
	}
	return docs, rows.Err()
}
